# ============================================================================
# Post-Provision Setup Script
# Runs automatically after 'azd provision' via azure.yaml hook
# ============================================================================
# Configures: .env file, RBAC roles, Python packages, Cosmos DB seed data
# ============================================================================

$ErrorActionPreference = "Stop"
$ProjectRoot = $PSScriptRoot | Split-Path -Parent

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host " Post-Provision Configuration" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan

# ---------- 1. Collect azd env values ----------
Write-Host "`n[1/5] Reading deployment outputs..." -ForegroundColor Yellow

# azd stores Bicep outputs using their exact camelCase names
$foundryEndpoint    = azd env get-value foundryEndpoint 2>$null
$cosmosEndpoint     = azd env get-value cosmosEndpoint 2>$null
$cosmosDatabaseName = azd env get-value cosmosDatabaseName 2>$null
$modelDeployment    = azd env get-value modelDeploymentName 2>$null
$apimGatewayUrl     = azd env get-value apimGatewayUrl 2>$null

# Standard azd env vars
$subscriptionId     = azd env get-value AZURE_SUBSCRIPTION_ID 2>$null
$resourceGroup      = azd env get-value AZURE_RESOURCE_GROUP 2>$null
$envName            = azd env get-value AZURE_ENV_NAME 2>$null

# Fallbacks
if (-not $subscriptionId) {
    $subscriptionId = (az account show --query id -o tsv)
}
if (-not $resourceGroup) {
    if ($envName) { $resourceGroup = "rg-$envName" }
    else { $resourceGroup = "rg-challenge5" }
}
if (-not $cosmosDatabaseName) {
    $cosmosDatabaseName = "helpdesk-db"
}
if (-not $modelDeployment) {
    $modelDeployment = "gpt-4o"
}

Write-Host "  Foundry Endpoint: $foundryEndpoint"
Write-Host "  Cosmos Endpoint:  $cosmosEndpoint"
Write-Host "  Cosmos Database:  $cosmosDatabaseName"
Write-Host "  Model:            $modelDeployment"
Write-Host "  Subscription:     $subscriptionId"
Write-Host "  Resource Group:   $resourceGroup"

# ---------- 2. Write .env file ----------
Write-Host "`n[2/5] Writing .env file..." -ForegroundColor Yellow
$envFile = Join-Path $ProjectRoot ".env"

@"
# Challenge 5 - Environment Variables (auto-generated by postprovision)
FOUNDRY_ENDPOINT=$foundryEndpoint
AZURE_SUBSCRIPTION_ID=$subscriptionId
AZURE_RESOURCE_GROUP=$resourceGroup
MODEL_DEPLOYMENT_NAME=$modelDeployment
AGENT_NAME=IT-HelpDesk-Agent
APIM_GATEWAY_URL=$apimGatewayUrl
COSMOS_ENDPOINT=$cosmosEndpoint
COSMOS_DATABASE=$cosmosDatabaseName
"@ | Set-Content -Path $envFile -Encoding UTF8

Write-Host "  Written to: $envFile" -ForegroundColor Green

# ---------- 3. Assign RBAC Roles ----------
Write-Host "`n[3/5] Assigning RBAC roles..." -ForegroundColor Yellow
$currentUserId = az ad signed-in-user show --query id -o tsv 2>$null

if ($currentUserId) {
    $scope = "/subscriptions/$subscriptionId/resourceGroups/$resourceGroup"

    # Azure AI User (for Foundry agent operations)
    Write-Host "  Assigning Azure AI User..."
    az role assignment create --assignee $currentUserId --role "Azure AI User" --scope $scope --output none 2>$null

    # Cognitive Services OpenAI User
    Write-Host "  Assigning Cognitive Services OpenAI User..."
    az role assignment create --assignee $currentUserId --role "Cognitive Services OpenAI User" --scope $scope --output none 2>$null

    # Cosmos DB Data Contributor
    Write-Host "  Assigning Cosmos DB Built-in Data Contributor..."
    $cosmosName = azd env get-value foundryName 2>$null
    if (-not $cosmosName) {
        $cosmosName = (az cosmosdb list --resource-group $resourceGroup --query "[0].name" -o tsv 2>$null)
    }
    if ($cosmosName) {
        az cosmosdb sql role assignment create `
            --account-name $cosmosName `
            --resource-group $resourceGroup `
            --scope "/" `
            --principal-id $currentUserId `
            --role-definition-id "00000000-0000-0000-0000-000000000002" `
            --output none 2>$null
    }

    Write-Host "  RBAC roles assigned." -ForegroundColor Green
} else {
    Write-Host "  [WARN] Could not determine current user. Skipping RBAC." -ForegroundColor Yellow
}

# ---------- 4. Install Python Dependencies ----------
Write-Host "`n[4/5] Installing Python dependencies..." -ForegroundColor Yellow
$reqFile = Join-Path $ProjectRoot "requirements.txt"
if (Test-Path $reqFile) {
    pip install -r $reqFile --quiet 2>&1 | Out-Null
    Write-Host "  Dependencies installed." -ForegroundColor Green
} else {
    Write-Host "  [WARN] requirements.txt not found." -ForegroundColor Yellow
}

# ---------- 5. Seed Cosmos DB ----------
Write-Host "`n[5/5] Seeding Cosmos DB with sample data..." -ForegroundColor Yellow
$seedScript = Join-Path $ProjectRoot "scripts" "seed_cosmos.py"
if (Test-Path $seedScript) {
    try {
        python $seedScript 2>&1
        Write-Host "  Cosmos DB seeded." -ForegroundColor Green
    } catch {
        Write-Host "  [WARN] Seed script failed: $_" -ForegroundColor Yellow
        Write-Host "  You can retry manually: python scripts/seed_cosmos.py" -ForegroundColor Yellow
    }
} else {
    Write-Host "  [WARN] seed_cosmos.py not found." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "============================================" -ForegroundColor Green
Write-Host " Setup Complete!" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green
Write-Host ""
Write-Host "To start the application, run:" -ForegroundColor Cyan
Write-Host "  .\scripts\start.ps1" -ForegroundColor White
Write-Host ""
Write-Host "Or start each server manually:" -ForegroundColor Cyan
Write-Host "  python src/backend/app.py     # Backend on port 8000" -ForegroundColor White
Write-Host "  python src/frontend/app.py    # Frontend on port 5000" -ForegroundColor White
Write-Host ""
